import numpy as np
import csv
import os
import random
import cv2
import torch
from torch.utils.data import Dataset
from collections import Counter

#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# https://scikit-learn.org/stable/modules/cross_validation.html#stratification
from sklearn.model_selection import train_test_split 


class DataLoader:
    """
    The DataLoader class module is responsible for fetching the data. This includes,
        1) image data of the thumbnails to be sent through the edge extractor module,
        2) the extracted edge contours,
        3) tabular data metrics.
    The class requires an multiple directories to be specified, namely: the image directory, the edge directory, and the tabular metric directory containing the csv file with the tabular data.
    It is responsoble for merging data into a dictionary which can be used for data fetching later in the pipeline.
    """
    def __init__(self):
        """
        Initializes the DataLoader module.
        """
        self._imageDirectory : str = ""
        self._edgeDirectory : str = ""
        self._metricDirectory : str = ""
        self._data : dict = {} # self._data[imageName] = {"name": imageName, "edge_path": path, "metrics": metrics, "class": category}
        self._train : list = []                     # data used for training
        self._validation : list = []                # data used for validation
        self._test : list = []                      # data used for testing
        self._meanOfTrainedMetrics : np.ndarray     # used for normalizing metric vectors
        self._stdOfTrainedMetrics : np.ndarray      # standard deviation of metric vectors used for training -> used for normalization
    
    def load(self, imagesPath : str, edgesPath : str, metricsPath : str, csvFileName: str):
        """
        Takes the respective paths (path for images, path for edge contours, path for tabular metric file, and csv filename) and loads the respective data into memory.
        The function iteratively scans the edge directory, checks the edges filenames against the data provided by the csv file and saves the matching pairs to `self._data` which is the internal dictionary.

        Args:
            imagesPath (str): Path to the images to be processed.
            edgesPath (str): Path to the edge contours.
            metricsPath (str): Path to the directory containing the output data in .csv format (generated by the STEP categorizer program).
            csvFileName (str): The absolute path for the secondary_data.csv file generated by the STEP categorizer utility.
        Returns:
            None.
        Raises:
            FileNotFoundError: If the csv file which is provided doesnt exist.
        """
        self._setImageDirectory(imagesPath)
        self._setEdgeDirectory(edgesPath)
        self._setMetricDirectory(metricsPath)
        
        if self._imageDirectory == "" or self._edgeDirectory == "" or self._metricDirectory == "":
            print(f"[DataLoader] > Error: load() requires three correct paths but one or more is not parsed.")
            return
        
        # get fuilenames in edge directory
        edgesList = os.listdir(self._edgeDirectory)
        edgeFiles = {}

        for f in edgesList:
            bname = f.split('.')[0].lower().strip()

            # temporary fix for _normal problem!!!! refactor stepmaster code so images and contours arent generated with prefix _normal. The following line just removes _normal prefix
            bname = bname.replace("_normal", "")
            
            edgeFiles[bname] = f
        
        if len(edgeFiles) == 0:
            print(f"[DataLoader] > WARNING: 0 internal files found in {self._edgeDirectory}.")
        
        # check filenames from edgedir against the ones in csv and append to datastructure
        with open(csvFileName, "r", encoding="utf-8") as file:
            csvReader = csv.reader(file)

            next(csvReader)
            # filename,
            for row in csvReader:
                # bname = row[0].split(".")[0].lower().strip() # csv row name without extension
                fullName = row[0].lower().strip()
                bname = os.path.splitext(fullName)[0]
                
                if bname in edgeFiles: # if edge contours name exists in csv file
                    img = edgeFiles[bname]
                    imgPath = os.path.join(self._edgeDirectory, img) # full path

                    # # characteristics to be loaded --- solidletters
                    # category = row[1]
                    # shells = row[2]
                    # solids = row[3]
                    # edges = row[4]
                    # faces = row[5]
                    # vertices = row[6]
                    # wires = row[7]
                    # area = row[8]
                    # volume = row[9]
                    # edge_long = row[10]
                    # edge_mid = row[11]
                    # edge_irregular = row[12]
                    # edge_short = row[13]
                    # edge_circular = row[14]
                    # edge_bspline = row[15]
                    # edge_line = row[16]
                    # edge_curved = row[17]
                    # edge_x_aligned = row[18]
                    # edge_y_aligned = row[19]
                    # edge_z_aligned = row[20]
                    # edge_axis_aligned = row[21]
                    # edge_none_aligned = row[22]
                    # face_planar = row[23]
                    # face_curved = row[24]
                    # bbox_x = row[29]
                    # bbox_y = row[26]
                    # bbox_z = row[27]
                    # bbox_square = row[28]
                    # bbox_vol = row[29]
                    # solid_vol = row[30]
                    # vol_dif = row[31]
                    # round_faces = row[32]
                    # perpendicular_faces = row[33]
                    # volumes_match = row [34]
                    # holed = row[35]
                    # holes = row[36]
                    # characteristics to be loaded --- traceparts
                    category = row[1]
                    shells = row[2]
                    solids = row[3]
                    edges = row[4]
                    faces = row[5]
                    vertices = row[6]
                    wires = row[7]
                    area = row[8]
                    volume = row[9]
                    edge_long = row[10]
                    edge_mid = row[11]
                    edge_irregular = row[12]
                    edge_short = row[13]
                    edge_circular = row[14]
                    edge_bspline = row[15]
                    edge_line = row[16]
                    edge_curved = row[17]
                    edge_x_aligned = row[18]
                    edge_y_aligned = row[19]
                    edge_z_aligned = row[20]
                    edge_axis_aligned = row[21]
                    edge_none_aligned = row[22]
                    face_planar = row[23]
                    face_curved = row[24]

                    # note to report: ---------------- check for removal of some characteristics to compare traceparts with solidletters lib (for traceparts)
                    bbox_x = row[29]
                    bbox_y = row[30]
                    bbox_z = row[31]
                    bbox_square = row[32]
                    bbox_vol = row[33]
                    solid_vol = row[34]
                    vol_dif = row[35]
                    round_faces = row[36]
                    perpendicular_faces = row[37]
                    volumes_match = row [38]
                    holed = row[39]
                    holes = row[40]
                    
                    characteristics = [
                        shells,
                        solids,
                        edges,
                        faces,
                        vertices,
                        wires,
                        area,
                        volume,
                        edge_long,
                        edge_mid,
                        edge_irregular,
                        edge_short,
                        edge_circular,
                        edge_bspline,
                        edge_line,
                        edge_curved,
                        edge_x_aligned,
                        edge_y_aligned,
                        edge_z_aligned,
                        edge_axis_aligned,
                        edge_none_aligned,
                        face_planar,
                        face_curved,
                        bbox_x,
                        bbox_y,
                        bbox_z,
                        bbox_square,
                        bbox_vol,
                        solid_vol,
                        vol_dif,
                        round_faces,
                        perpendicular_faces,
                        volumes_match,
                        holed,
                        holes
                    ]

                    characteristics = [self._metricConverter(metric=m) for m in characteristics]
                    self._saveMatch(imageName=img, path=imgPath, metrics=characteristics, category=category)
                else:
                    print(f"[Dataloader] > Error: Edge contours could not be matched with metrics for descriptor: {bname}, in the csv file. Skipping.")
                    print(f"[DEBUG] Could not match CSV file '{bname}' to any file in edge directory. Keys in edgeFiles: {list(edgeFiles.keys())[:5]}...")
                    continue
    
    def _saveMatch(self, imageName: str, path : str, metrics : list, category : str = ""):
        if path == "" or metrics == []:
            print(f"[DataLoader] > Error: Could not save match. Either the path is not specified or the metrics vector is not parsed. Skipping.")
            return
        
        if category == "Uncategorized":
            category = ""
        
        self._data[imageName] = {"name": imageName, "edge_path": path, "metrics": metrics, "class": category}
        print(f"[DataLoader] > Saved entry: ({imageName}:{category}), with path: {path}")
    
    def splitData(self, trainRatio : float, validationRatio : float, testRatio : float):
        """
        Splits the data into stratisfied train, validation, and test with the given ratios. This implies each data portion contains a class sample.

        Args:
            trainRatio (float): Ratio of training data.
            validationRatio (float): Ratio of validation data.
            testRatio (float): Ratio of testing data.
        Returns:
            None.
        """
        # if another library is used it would be smart to create a new helper func to assert the ground truth for that library such as the one used below
        # self.classifySolidLettersLib() # ground truth for classes (for solidLetters lib)
        
        allParts = []
        allLabels = []
        
        for key, entry in self._data.items():
            category = str(entry.get("class", "")).strip()
            
            # skip uncateorizaziable entries
            if category == "":
                continue
            
            allParts.append(entry.get("name", ""))
            allLabels.append(entry.get("class"))

        print(f"[DataLoader] > Total valid samples found for training: {len(allParts)}")
        # #indexes and assignmetn
        # trainIndex = int(len(allParts) * trainRatio)
        # validationIndex = int(len(allParts) * validationRatio) + trainIndex
        # testIndex = int(len(allParts) * testRatio) + validationIndex
        
        # random.shuffle(allParts)
        
        # self._train = allParts[:trainIndex]
        # self._validation = allParts[trainIndex:validationIndex]
        # self._test = allParts[validationIndex:]

        classCounter = Counter(allLabels)
        minSampleAmount = 7 # min amount of samples allowed to be in a given class. parametr is for stratisfying
        
        filteredParts = []
        filteredLabels = []

        for part, label in zip(allParts, allLabels):
            if classCounter[label] >= minSampleAmount:
                filteredParts.append(part)
                filteredLabels.append(label)
        
        allParts = filteredParts
        allLabels = filteredLabels
        
        if len(allParts)  == 0:
            print(f"[DataLoader] > After filtering the parts in order to stratisfy the data no samples is left. More data required.")
        
        # outfilter datapunkter der ikke kan stratifiseres
        self._data = {part: self._data[part] for part in allParts}
        
        self._train, secondSplitParts, _, secondSplitLabels = train_test_split(allParts, allLabels, train_size=trainRatio, test_size=validationRatio+testRatio, stratify=allLabels, random_state=0)

        testSize = testRatio / (validationRatio + testRatio)
        
        self._validation, self._test, _, _ = train_test_split(secondSplitParts, secondSplitLabels, test_size=testSize, stratify=secondSplitLabels, random_state=0)
        
        # mean of the metrics (determining z score variable: meanOfMetrics to normalize metrics later on)
        metricsMean = np.array([self._data[metric]["metrics"] for metric in self._train], dtype=np.float32)
        self._meanOfTrainedMetrics = np.mean(metricsMean, axis=0)
        self._stdOfTrainedMetrics = np.std(metricsMean, axis=0) + 1e-16
        
        print(f"[DataLoader] > Data has been split into train, validation, and test sets successfully.")
    
    # getters
    def getEdge(self, name : str) -> np.ndarray:
        """
        Returns the edge contour given its filename. This function normalizes the image to have pixel intensity between 0 and 1

        Args:
            name (str): Name of the desired edge contour.

        Returns:
            np.ndarray: The specified contour.
        """
        path = self._data[name]["edge_path"]
        contour = cv2.imread(path).astype(np.float32)
        contour = contour / 255.0 # https://www.geeksforgeeks.org/computer-vision/normalize-an-image-in-opencv-python/
        contour = np.transpose(contour, (2, 0, 1)) # https://docs.pytorch.org/tutorials/intermediate/memory_format_tutorial.html
        return contour
    
    def getMetric(self, name : str) -> np.ndarray:
        """
        Returns the tabular data metric given the specified filename. This function normalizes the tabular data via z-score normalization using the mean and standard deviation
        calculated using the training data preventing data leakage.

        Args:
            name (str): Name of the file for which the tabular metric should be returned.

        Returns:
            np.ndarray: Tabular metric.
        """
        metrics = self._data[name]["metrics"]
        metrics = np.array(metrics, dtype=np.float32)
        metrics = (metrics - self._meanOfTrainedMetrics) / self._stdOfTrainedMetrics # formular: Z = (X - mu)/sigma --- https://www.geeksforgeeks.org/machine-learning/feature-engineering-scaling-normalization-and-standardization/
        return metrics

    def getData(self) -> dict:
        """
        Get the internal class dictionary containing following structure:
        {"name": imageName, "edge_path": path, "metrics": metrics, "class": category}.

        Returns:
            dict: data dictionary.
        """
        return self._data
    
    def getTrain(self):
        """
        Get the train data split.

        Raises:
            ValueError: If a data split hasnt been made or train is None.

        Returns:
            list: The train split.
        """
        if self._train is not None:
            return self._train
        else:
            raise ValueError("[DataLoader] > ValueError: train data is None.")
    
    def getValidation(self):
        """
        Get the validation data split.

        Raises:
            ValueError: If a data split hasnt been made or validation is None.

        Returns:
            list: The train split
        """
        if self._validation is not None:
            return self._validation
        else:
            raise ValueError("[DataLoader] > ValueError: validation data is None.")
    
    def getTest(self):
        """
        Get the test data split.

        Raises:
            ValueError: If a data split hasnt been made or test is None.

        Returns:
            list: The test data split.
        """
        if self._test is not None:
            return self._test
        else:
            raise ValueError("[DataLoader] > ValueError: test data is None.")
    
    def getNumOfClasses(self):
        """
        Returns the number of classes in the data.

        Returns:
            int: The number of total classes regardless of data split.
        """
        classes = set()
        
        for entry in self._data.values():
            category = entry.get("class", "").strip()
            
            if category != "":
                classes.add(category)
        
        return len(classes)
    
    def getClassNames(self):
        """
        Get the unique class names.

        Returns:
            list: A sorted list of all unique class names in the data.
        """
        classes = set()
        
        for entry in self._data.values():
            category = entry.get("class", "").strip()

            if category != "":
                classes.add(category)
        
        return sorted(list(classes), key=lambda c: (c.lower(), not c.islower()))
    
    # setters
    def _setImageDirectory(self, path : str):
        if path == "":
            print(f"[DataLoader] > Error: setImagePath expected a raw string but got an empty one instead.")
            return
        
        self._imageDirectory = path
    
    def _setEdgeDirectory(self, path : str):
        if path == "":
            print(f"[DataLoader] > Error: setEdgePath expected a raw string but got an empty one instead.")
            return

        self._edgeDirectory = path
    
    def _setMetricDirectory(self, path : str):
        if path == "":
            print(f"[DataLoader] > Error: setMetricPath expected a raw string but got an empty one instead.")
            return

        self._metricDirectory = path
    
    def _metricConverter(self, metric : str) -> float:
        metric = str(metric).strip().lower()
        
        # booleans
        if metric == "true":
            return 1.0
        if metric == "false":
            return 0.0
        
        # empty metrics
        if metric == "":
            return 0.0
        
        # numbers
        try:
            return float(metric)

        except ValueError:
            print(f"[DataLoader] > Warning: Could not convert metric to float when loading data.")
            try:
                return float(metric.replace(",", "."))
            except ValueError:
                print(f"[DataLoader] > Warning: ValueError occured when converting metric to float. Returning 0.0 instead.")
                return 0.0
    
    # def classifySolidLettersLib(self):
    #     print("[DataLoader > Initializing the classification of the SolidLetters library.]")
    #     for entry in self._data.values():
    #         className = str(entry.get("name", "")).strip()
    #         className = os.path.splitext(className)[0]
    #         entry["class"] = className[:1].lower()
    #         print(f"[DataLoader] > Ground truth established for data entry {entry.get('name')} as {className}.")
    #     print("[DataLoader] > The contours from SolidLetters has been successfully classified - class ground truth is now available.")
    
    def classifySolidLettersLib(self):
        """
        This function establishes the ground truth e.g. labels for the SolidLetters library.
        It iterates through all loaded edge contours, and extracts the labels from the filenames prefix. The function handles upper and lower case filenames,
        such that both types will be labeled as a class e.g. the letter `a` will have classes `a` and `A`.
        
        Args:
            None.
        Returns:
            None.
        """
        print("[DataLoader > Initializing the classification of the SolidLetters library.]")
        for entry in self._data.values():
            className = str(entry.get("name", "")).strip()
            className = os.path.splitext(className)[0]
            
            # Extract just the first letter
            first_char = className[:1]
            
            # Check if name contains "upper" or "lower" (using .lower() for a case-insensitive check)
            if "upper" in className.lower():
                entry["class"] = first_char.upper()
            elif "lower" in className.lower():
                entry["class"] = first_char.lower()
            else:
                # Fallback just in case neither is in the name
                entry["class"] = first_char
                
            print(f"[DataLoader] > Ground truth established for data entry {entry.get('name')} as {entry['class']}.")
        print("[DataLoader] > The contours from SolidLetters has been successfully classified - class ground truth is now available.")
    
    def classifyTracePartsLib(self, csvPath):
        """
        This function establishes the ground truth e.g. labels for the TraceParts library using a metadata .csv file.
        This is done by making a lookup table from the provided .csv file and iterating through it to extract the given filenames and classs.
        Each filename and class is saved to the lookup table while invalid data entries are ignored.

        Args:
            csvPath (str): Absolute file path for the TraceParts metadata .csv file (e.g. `categories.csv`).
        Returns:
            None.
        Raises:
            FileNotFoundError: If the provided input argument is invalid or the .csv filepath does not exist.
        """
        if csvPath is None:
            print("[DataLoader] > input parameter 'csvPath' cannot be of type None. Function requires metadata csv file to exist.")
            return
        
        tempDict: dict = {}
        
        with open(csvPath, "r", encoding="utf-8") as file:
            csvReader = csv.reader(file, delimiter=';')
            
            next(csvReader)
            
            for row in csvReader:
                if len(row) == 1 and "\t" in row[0]:
                    row = row[0].split("\t")
                
                if len(row) < 5:
                    continue
                
                partName = row[0].split(".")[0].lower().strip()
                partCategory = row[4].lower().strip()
                
                # if partName in self._data.keys():
                tempDict[partName] = partCategory
        
        for entry in self._data:
            bname = entry.split(".")[0].lower().strip()
            if bname in tempDict:
                category = tempDict.get(bname)
                if category != "" and category != "uncategorized":
                    self._data[entry]["class"] = category
                else:
                    self._data[entry]["class"] = ""
            else:
                self._data[entry]["class"] = ""
    
    # def _getCharacteristics(self, csvFile : str):
    #     if self._metricDirectory == "" or csvFile == "":
    #         print(f"[DataLoader] > Error: _getCharacteristics cannot execute when no metrics directory is set. check filename.")
    #         return
        
    #     with open(csvFile, "r") as file:
    #         csvReader = csv.reader(file)


# DL = DataLoader()
# DL.load("dd", "dd", r"D:\OneDrive - Aarhus universitet\Aarhus Universitet\6. semester\Bachelorprojekt\step_categorizer-master\output", "secondary_data.csv")


class DataWrapper(Dataset):
    """
    This class only exists to integrate the custom data loader module into Pytorch.
    It takes the numpy arrays given the train, validation and test data and loads it into Pytorch tensors while assigning class labels of type `int` to the respective data points.
    """
    def __init__(self, dataLoader: DataLoader, split="train"): #: DataLoader <<<<<<<<<-------
        """
        Initializes pytorch dataset splits.

        Args:
            dataLoader (DataLoader): The custom dataloader module containing the data to be processed.
            split (str, optional): Specifies what split to retrieve (e.g. train, validation, or test). Defaults to "train".

        Raises:
            ValueError: If the provided split string is invalid.
        """
        self._loader = dataLoader
        classes = self._loader.getClassNames()
        self._classDict: dict = {className: i for i, className in enumerate(classes)}
        
        if split == "train":
            self._data = self._loader._train
        elif split == "validation":
            self._data = self._loader._validation
        elif split == "test":
            self._data = self._loader._test
        else:
            raise ValueError("The split fetched from the custom data loader 'dataLoader' must be specified as either: 'train', 'validation', or 'test'.")
    
    def __len__(self):
        """
        Returns the total number of samples in the specified dataset split. This function must be implemented in the datawrapper:
        https://docs.pytorch.org/tutorials/beginner/basics/data_tutorial.html#creating-a-custom-dataset-for-your-files

        Returns:
            int: The length of the data split.
        """
        return len(self._data)
    
    def __getitem__(self, index):
        """
        Get a single item sample from the dataset. The function extracts the normalized edge contours and the normalized metrics, converts
        them into respective pytorch tensors such that they can be processed. The class ground truths are also mapped to the respective samples in each tensor.

        Args:
            index (int): Specifies the index of what item sample to retrieve.

        Returns:
            tuple: A tupple of size 3 containing:
                - edgeTensor (torch.Tensor): The tensor containing visual data.
                - metricTensor (torch.Tensor): The tensor containing tabular data.
                - labelTensor (torch.tensor): Class ground truths.
        """
        img = self._data[index]
        
        edge = self._loader.getEdge(img)
        metric = self._loader.getMetric(img)
        classLabel = self._loader._data[img]["class"] # get ground truth class for image
        
        label = self._classDict[classLabel]
        
        edgeTensor = torch.tensor(edge, dtype=torch.float32)
        metricTensor = torch.tensor(metric, dtype=torch.float32)
        labelTensor = torch.tensor(label, dtype=torch.long)
        
        return edgeTensor, metricTensor, labelTensor
        